// vue_ts_shopping_app/src/components/CartBox.vue
<template>
<div class='cart-box-container'>
  <cart-item-card
    v-for='(cartItem, index) in cartItems'
    v-on:changeNum='changeNum'
    :key='cartItem.id'
    :index='index'
    :cartItem='cartItem'
  />
  <div>合計金額 : {{ totalFee }}円</div>
  <reset-button v-on:resetCart='resetCart' />
</div>
</template>

<script lang='ts'>
import { Component, Prop, Vue, Emit } from 'vue-property-decorator';
import CartItemCard from './CartItemCard.vue';
import ResetButton from './ResetButton.vue';
import { CartItem } from '../interface';

@Component({
  components: {
    CartItemCard,
    ResetButton,
  },
})
export default class CartBox extends Vue {
  @Prop()
  public cartItems!: CartItem[];

  @Emit('resetCart')
  public resetCart(): void {}

  @Emit('changeNum')
  public emitChageNum(changedNum: number, index: number): void {}

  public changeNum(changedNum: number, index: number): void {
    this.emitChageNum(changedNum, index);
  }

  public changeCartItems(newNumber: number, index: number): void {
    if (newNumber > 0) {
      this.cartItems[index].quantity = newNumber;
    } else {
      this.cartItems.splice(index, 1);
    }
  }

  public get totalFee(): number {
    let sum: number = 0;
    for (const cartItem of this.cartItems) {
      sum += cartItem.price * cartItem.quantity;
    }
    return sum;
  }
}
</script>

// react_shopping_app/src/components/CartBox.js
import React from 'react'
import ResetButton from './ResetButton'
import CartItem from './CartItem'

export default class cartBox extends React.Component{
    constructor(props) {
        super(props)
        this.changeNum = this.changeNum.bind(this)
        this.resetCart = this.resetCart.bind(this)
    }
    changeNum(newNumber, index) {
        this.props.changeNum(newNumber, index)
    }
    resetCart() {
        this.props.resetCart()
    }
    render() {
        const cartItem = this.props.cartItems.map( (cartItem, index) => {
            return (
                <CartItem
                    key={cartItem.name }
                    changeNum={ this.changeNum}
                    index={ index }
                    cartItem={ cartItem }
                />
            )
        })
        let sum = 0
        for (let i = 0; i < this.props.cartItems.length; i++) {
            sum += this.props.cartItems[i].price * this.props.cartItems[i].quantity
        }
        return (
            <div className="cart-box-container">
                {cartItem}
                <div>合計金額 : { sum }円</div>
                <ResetButton resetCart={ this.resetCart }/>
            </div>
        )
    }
}
