// vue_cli_shopping_app/src/components/ResetButton.vue
<template>
<button 
class="btn-square"
style="background: #fd9535;"
v-on:click="$emit('resetCart')"
>reset cart</button>
</template>

<style scoped>
.btn-square {
  display: inline-block;
  padding: 0.5em 1em;
  text-decoration: none;
  background: #668ad8;/*ボタン色*/
  color: #FFF;
  border-radius: 3px;
}
</style>

// react_shopping_app/src/components/ResetButton.js
import React from 'react'

export default class ResetButton extends React.Component{
    constructor(props) {
        super(props)
        this.handleOnClick = this.handleOnClick.bind(this)
    }
    handleOnClick() {
        this.props.resetCart()
    }
    render() {
        return (
            <button
                onClick={this.handleOnClick}
                className="btn-square"
                style={{ background: '#fd9535' } }
            >reset cart</button>
        )
    }
}
