// react_shopping_app/src/components/ResetButton.js
import React from 'react'

export default class ResetButton extends React.Component{
    constructor(props) {
        super(props)
        this.handleOnClick = this.handleOnClick.bind(this)
    }
    handleOnClick() {
        this.props.resetCart()
    }
    render() {
        return (
            <button
                onClick={this.handleOnClick}
                className="btn-square"
                style={{ background: '#fd9535' } }
            >reset cart</button>
        )
    }
}

// vue_ts_shopping_app/src/components/ResetButton.vue
<template>
<button class='btn-square' style='background: #fd9535;' v-on:click='resetCart'>reset cart</button>
</template>

<script lang='ts'>
import { Component, Vue, Emit } from 'vue-property-decorator';

@Component
export default class ResetButton extends Vue {
  @Emit('resetCart')
  public resetCart(): void {}
}
</script>
