// vue_cli_shopping_app/src/components/ProductsBox.vue
<template>
<div class="products-box-container">
    <rich-item-card 
        v-for="product in products" 
        :key="product.id"
        v-on:addCart="$emit('addCart',product)" 
        :product="product"
    />
</div>
</template>

<script>
import RichItemCard from './RichItemCard'

export default {
    props: ['products'],
    components: {
        'rich-item-card': RichItemCard,
    }
}
</script>

<style scoped>
.products-box-container{
width: 60%;
display: inline-block;
vertical-align:  top;
}  
</style>

// react_shopping_app/shopping-app/src/components/ProductsBox.js
import React from 'react'
import RichItemCard from './RichItemCard'

export default class ProductsBox extends React.Component { 
    constructor(props) {
        super(props)
        this.addCart = this.addCart.bind(this)
    }
    addCart(product) {
        this.props.addCart(product)
    }
    render() {
        let richItemCards = this.props.products.map( (product) => {
            return (
                <RichItemCard
                    product={product}
                    key={product.id}
                    addCart={() => { this.addCart(product) }}
                />
            )
        })
        return (
            <div className="products-box-container">
                {richItemCards}
            </div>
        )
    }
}
