// react_shopping_app/src/components/CartItem.js
import React from 'react'

export default class CartItem extends React.Component {
    constructor(props) {
        super(props)
        this.addCart = this.addCart.bind(this)
        this.changeNum = this.changeNum.bind(this)
    }
    addCart() {
        this.props.addCart()
    }
    changeNum(e) {
        this.props.changeNum(e.target.value, this.props.index)
    }
    render() {
        return (
            <div className="cart-item-container">
                <h3 className="cart-item-title">{ this.props.cartItem.name }</h3>
                <p className="cart-item-title">{ this.props.cartItem.price }円</p>
                <input type="number"
                    className='cart-item-input'
                    value={this.props.cartItem.quantity}
                    onChange={this.changeNum}
                />
            </div>
        )
    }
}

// vue_cli_shopping_app/src/components/CartItem.vue
<template>
<div class="cart-item-container">
    <h3 class="cart-item-title">{{ cartItem.name }}</h3>
    <p class="cart-item-title">{{ cartItem.price }}円</p>
    <input type="number"
    class='cart-item-input'
    v-bind:value = "cartItem.quantity"
    v-on:input="$emit('changeNum',$event.target.value,index)"
    />
</div>
</template>

<script>
export default {
    props: ['cartItem', 'index'],
}
</script>

<style scoped>
.cart-item-title{
  display: inline-block;
}

.cart-item-input{
    display: inline-block;
    width: 20%;
    height: calc(1.5em + 0.75rem + 2px);
    padding: 0.375rem 0.75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da;
    border-radius: 0.25rem;
}
</style>
