// react_shopping_app/shopping-app/src/components/ItemsIndex.js
import React from 'react'
import ProductsBox from './ProductsBox'
import CartBox from './CartBox'

export default class ItemIndex extends React.Component{
    constructor(props) {
        super(props)
        this.state = {
            cartItems: []
        }
        this.addCart = this.addCart.bind(this)
        this.resetCart = this.resetCart.bind(this)
        this.changeCartItems = this.changeCartItems.bind(this)
    }
    addCart(product) {
        let isFounded = false
        let cartNumber = null
        for (let i = 0; i < this.state.cartItems.length; i++) {
            if (this.state.cartItems[i].name === product.name) {
                isFounded = true
                cartNumber = i
                break
            }
        }
        // const cartItems = this.state.cartItems;
        if (isFounded) {
            this.setState(function (state) {
                state.cartItems[cartNumber].quantity += 1
                return {
                    cartItems: state.cartItems
                }
            })
            // this.setState({ cartItem: cartItems[cartNumber].quantity += 1})
        } else {
            this.setState(function (state) {
                return {
                    cartItems: state.cartItems.concat({ name: product.name, price: product.price, quantity: 1 })
                }
            })
        }
    }
    changeCartItems(newNumber, index) {
        const cartItems = this.state.cartItems
        if (newNumber > 0) {
            cartItems[index].quantity = Number(newNumber)
        } else {
            cartItems.splice(index, 1)
        }
        this.setState({ cartItems: cartItems })
    }
    resetCart() {
        this.setState({ cartItems:[]})
    }
    render() {
        return (
            <div className="item-index-container">
                <ProductsBox
                    addCart={this.addCart}
                    products={this.props.products} 
                />
                <CartBox
                    resetCart={this.resetCart}
                    changeNum={this.changeCartItems}
                    cartItems={this.state.cartItems}
                />
            </div>
        )
    }
}

// vue_cli_shopping_app/src/components/ItemsIndex.vue
<template>
     <div class="item-index-container">
        <products-box v-on:addCart="addCart" :products="products"/>
        <cart-box v-on:resetCart="resetCart" v-on:changeNum="changeCartItems" :cartItems="cartItems"/>
    </div>
</template>

<script>

import ProductsBox from './ProductsBox'
import CartBox from './CartBox'

export default {
    props: ['products'],
    data: function () {
        return {
            cartItems: []
        }
    },
    methods: {
        addCart: function (product) {
            let isFounded = false
            let cartNumber;
            for (let i = 0; i < this.cartItems.length; i++) {
                if (this.cartItems[i].name === product.name) {
                    isFounded = true
                    cartNumber = i
                    break
                }
            }
            if (isFounded) {
                this.cartItems[cartNumber].quantity += 1
            } else {
                this.cartItems.push({ name: product.name, price: product.price, quantity: 1 })
            }
        },
        changeCartItems: function (newNumber, index) {
            if (newNumber > 0) {
                this.cartItems[index].quantity = Number(newNumber)
            } else {
                this.cartItems.splice(index, 1)
            }
        },
        resetCart: function () {
            this.cartItems = []
        }
    },
    components: {
        'products-box': ProductsBox,
        'cart-box': CartBox,
    }
}
</script>
